### ISSUE TITLE
The examples with line segments in the create.scatterplot doesn't work

### ISSUE THREAD

**Issue by ZhuyuQ** [uclahs-cds/public-R-BoutrosLab-plotting-general#55] opened 2022-10-24 21:58 UTC
The following sample code in the `create.scatterplot` doesn't work.

```r
# With line segments
line.data <- data.frame(
    group = c('A','B','C'),
    x = sample(1:10,3),
    y = sample(1:10,3),
    z = sample(1:10,3)
    );

create.scatterplot(
    (x+y+z) ~ group,
    line.data,
    filename = tempfile(pattern = 'Scatterplot_with_LineSegments', fileext = '.tiff'),
    cex = 0,
    add.line.segments = TRUE,
    line.start = list(
	rep(0,nrow(line.data)), 
	line.data$x,
	c(line.data$x + line.data$y)
	),
    line.end = list(
	line.data$x, 
	c(line.data$x + line.data$y),
	c(line.data$x + line.data$y + line.data$z)
	),
    line.col = list('red','blue','green'),
    line.lwd = list(3,3,3),
    resolution = 200
    );
```

**Comment by stefaneng** [comment] 2023-01-09 19:51
I think the issue is fixed by converting group to a factor but I am not sure what the plot was designed to look like

``` r
suppressPackageStartupMessages(library(BoutrosLab.plotting.general));
line.data <- data.frame(
    group = as.factor(c('A','B','C')),
    x = sample(1:10,3),
    y = sample(1:10,3),
    z = sample(1:10,3)
    );

create.scatterplot(
    (x+y+z) ~ group,
    line.data,
    cex = 0,
    add.line.segments = TRUE,
    line.start = list(
        rep(0,nrow(line.data)), 
        line.data$x,
        c(line.data$x + line.data$y)
    ),
    line.end = list(
        line.data$x, 
        c(line.data$x + line.data$y),
        c(line.data$x + line.data$y + line.data$z)
    ),
    line.col = list('red','blue','green'),
    line.lwd = list(3,3,3),
    resolution = 200
    )
```

![](https://i.imgur.com/FVONPVx.png)

<sup>Created on 2023-01-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ZhuyuQ** [comment] 2023-01-09 21:13
Yes, it works. Thanks!
Zhuyu

**Comment by dan-knight** [comment] 2023-01-10 01:44
> I think the issue is fixed by converting group to a factor but I am not sure what the plot was designed to look like

Is this conversion something we want to add to the function as a kind of type guard?

**Closed** 2023-02-04 19:10 UTC
